services:
  pi:
    build:
      context: .
    environment:
      TZ: "Europe/Warsaw"
    image: sniffer-server
    ports:
      - "8008:8080"
    volumes:
      - /opt/app/vehicleCapacities.json:/app/resources/vehicleCapacities.json #to map json file with capacities
